name: image build

on:
  push:
    branches: [main]
    paths:
    - 'images/**/Dockerfile'
  workflow_dispatch:
    inputs:
      dockerfile_path:
          description: trigger a build (images/nettools/Dockerfile)
          default: null

jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.dockerfile_data.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Get dockerfile data
      id: dockerfile_data
      env:
        PY_SCRIPT_MODE: "dockerfile_changes"
      run: python3 ./bin/get-changed-files-data.py

    - name: Test Output
      run: |
        echo ${{ toJson(steps.dockerfile_data.outputs.matrix) }}  

  image_build:
    needs: get_changed_files
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        dockerfile: ${{ fromJson(needs.get_changed_files.outputs.matrix) }}  
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: |
        echo "Building image for Dockerfile at path: ${{ matrix.dockerfile }}"
        # Add your image build commands here