name: renovate docker images
on:
    workflow_dispatch:
      inputs:
        LOG_LEVEL:
            type: choice
            description: log level(info, debug)
            options:
            - info
            - debug
        RENOVATE_DRY_RUN:
            type: choice
            description: dry-run (https://docs.renovatebot.com/self-hosted-configuration/#dryrun)
            options:
            - "null"
            - extract
            - lookup
            - full
    schedule:
      # 11 AM EST every Monday
      - cron: '0 15 * * 1'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v43.0.13
      env:
        LOG_LEVEL: ${{ inputs.LOG_LEVEL }}
        RENOVATE_DRY_RUN: ${{ inputs.RENOVATE_DRY_RUN }}
      with:
        renovate-version: 41.123.0
        configurationFile: .github/renovate-docker.json
        token: '${{ github.token }}'
